#ifndef APP_APP_CONTROLLER_APP_STATE_MACHINE_H
#define APP_APP_CONTROLLER_APP_STATE_MACHINE_H

#include <stdbool.h>

typedef enum {
    APP_STATE_BOOT = 0,
    APP_STATE_HOME_ACTIVE,
    APP_STATE_HOME_PRESET_SELECT,
    APP_STATE_HOME_APPLYING_PRESET,
    APP_STATE_HOME_DISABLING_PERFORMANCE,
    APP_STATE_SETTINGS_MENU,
    APP_STATE_SETTINGS_EDIT,
    APP_STATE_SETTINGS_SAVE,
    APP_STATE_SETTINGS_DISCARD_CONFIRM,
    APP_STATE_SETTINGS_FACTORY_RESET_CONFIRM,
    APP_STATE_COUNT,
} app_state_t;

typedef enum {
    APP_STATE_EVENT_BOOT_COMPLETED = 0,
    APP_STATE_EVENT_ENCODER_ROTATED,
    APP_STATE_EVENT_ENCODER_SHORT_PRESSED,
    APP_STATE_EVENT_ENCODER_LONG_PRESSED,
    APP_STATE_EVENT_PRESET_APPLIED,
    APP_STATE_EVENT_PERFORMANCE_DISABLED,
    APP_STATE_EVENT_SETTINGS_EDIT_REQUESTED,
    APP_STATE_EVENT_SETTINGS_EDIT_CONFIRMED,
    APP_STATE_EVENT_SETTINGS_EDIT_CANCELLED,
    APP_STATE_EVENT_SETTINGS_SAVE_REQUESTED,
    APP_STATE_EVENT_SETTINGS_SAVE_SUCCEEDED,
    APP_STATE_EVENT_SETTINGS_SAVE_FAILED,
    APP_STATE_EVENT_SETTINGS_DISCARD_REQUESTED,
    APP_STATE_EVENT_SETTINGS_DISCARD_CONFIRMED,
    APP_STATE_EVENT_FACTORY_RESET_REQUESTED,
    APP_STATE_EVENT_FACTORY_RESET_CONFIRMED,
    APP_STATE_EVENT_FACTORY_RESET_FAILED,
    APP_STATE_EVENT_COUNT,
} app_state_event_t;

typedef enum {
    APP_STATE_ACTION_NONE = 0,
    APP_STATE_ACTION_APPLY_PRESET,
    APP_STATE_ACTION_DISABLE_PERFORMANCE,
    APP_STATE_ACTION_SAVE_AND_APPLY_SETTINGS,
    APP_STATE_ACTION_DISCARD_SETTINGS_AND_ENABLE_PERFORMANCE,
    APP_STATE_ACTION_FACTORY_RESET_AND_ENABLE_PERFORMANCE,
} app_state_action_t;

typedef struct {
    app_state_t next_state;
    app_state_action_t action;
} app_state_transition_t;

app_state_t app_state_machine_initial_state(void);
bool app_state_machine_transition(
    app_state_t current_state,
    app_state_event_t event,
    app_state_transition_t *transition);

#endif
